### ISSUE TITLE
Open the dialog box directly from the icon

### ISSUE THREAD

**Issue by rudrab** [popov895/better-end-session-dialog#3]
Hi,
Thanks a lot for this extension. This makes much more sense. This is a feature request.
However, the current workflow is to click the power-off icon-> a drop down list-> choose any of them-> dialog box is appearing. 
Is it possible to bypass the drop down altogether and just click the power icon will open the dialog box?

**Comment by popov895** [comment]
You can use `Ctrl+Alt+Del` to directly show the end session dialog, or try [this](https://extensions.gnome.org/extension/2917/bring-out-submenu-of-power-offlogout-button/) extension.
