### ISSUE TITLE
Add hibernation button

### ISSUE THREAD

**Issue by sxqsfun** [popov895/better-end-session-dialog#4]
Is it possible to add a hibernation button?

**Comment by popov895** [comment]
I'm afraid that it's quite difficult to implement this feature now, because GNOME doesn't provide a button for hibernation (as well as for sleep).

But I'll see what I can do for this.

**Comment by sxqsfun** [comment]
Yes. Hibernation is configured by me.
I tried adding the button myself, but it didn't work.
(I haven't written a gnome shell program)
```
                addButton({
                    label: _(`Hirbernate`, `button`),
                    setKeyFocus: this._type === 1,
                    action: () => {
                        const signalId = this.connect(`closed`, () => {
                            this.disconnect(signalId);
                            this._confirm(`ConfirmedHirbernate`).catch(logError);
                        });
                        this.close(true);
                    },
                });
```
It'll take effect with a command.(systemctl hibernate)

**Comment by popov895** [comment]
Fixed with 502c7eb636b152621f38d172159886e672defb1b.

**Comment by sxqsfun** [comment]
Thank you. It works.
But the internationalization of the text is not working, it was working fine before.

**Comment by popov895** [comment]
Yes, now someone has to translate it.
