### ISSUE TITLE
Bug: New version won't load.

### ISSUE THREAD

**Issue by Ticklezz** [popov895/better-end-session-dialog#6]
Latest version only gives me this. Gnome 43.9 Debian
![Screenshot from 2024-09-28 13-16-40](https://github.com/user-attachments/assets/d4eec64e-443a-4e57-b1b0-0abfa21c2e88)

**Comment by popov895** [comment]
I'm already aware of this issue, it's a packaging issue. The updated packages have already been submitted, please wait for the updates.

**Comment by popov895** [comment]
You can fix this manually by running the following command in the terminal:

```
$ glib-schema-compile ~/.local/share/gnome-shell/extensions/better-end-session-dialog@popov895.ukr.net/schemas
```
